Project/MyTend/MyTend/Controllers/DocsController.cs
namespace MyTend.Controllers
{
    using MyTender.Core;
    using MyTender.Security;
    using System.Web.Mvc;

    public class DocsController : BaseController
    {
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// Чяво
        /// </summary>
        /// <returns></returns>
        public ActionResult FAQ()
        {
            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// Инструкция заполнеиния заявок
        /// </summary>
        /// <returns></returns>
        public ActionResult Instruction()
        {
            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// Публичуе данные
        /// </summary>
        /// <returns></returns>
        public ActionResult PublicData()
        {
            return View();
        }

        /// <summary>
        /// Правила пользования сайтом
        /// </summary>
        /// <returns></returns>
        public ActionResult Rules()
        {
            return View();
        }

        /// <summary>
        /// Договор-оферта
        /// </summary>
        /// <returns></returns>
        public ActionResult Termins()
        {
            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// Правила заполнения профиля
        /// </summary>
        /// <returns></returns>
        public ActionResult AboutProfile()
        {
            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// О меню
        /// </summary>
        /// <returns></returns>
        public ActionResult AboutMenu()
        {
            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// Договор оферты
        /// </summary>
        /// <returns></returns>
        /*public ActionResult Aferta()
        {
            return View();
        }*/

        /// <summary>
        /// Договор оферты
        /// </summary>
        /// <returns></returns>
        public ActionResult Oferta()
        {
            return View();
        }

        public ActionResult AboutWork()
        {
            return RedirectToAction("Index", "Home");
        }

        public ActionResult AboutWork2()
        {
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Torgs()
        {
            return View();
        }
    }
}

Project/MyTend/MyTend/Views/Docs/AboutMenu.cshtml
@{
    ViewBag.Title = "О меню";
}

<h2>О меню</h2>

Project/MyTend/MyTend/Views/Docs/AboutProfile.cshtml
@{
    ViewBag.Title = "Правила заполнения профиля";
}

<h2>Правила заполнения профиля</h2>

<div style="color: #cc0001  ; font-weight: bold;">Уважаемый пользователь!</div>
<p><strong>Что бы стать заказчиком услуг, достаточно заполнить только начальную форму регистрации, загрузить фото на аватар, указать примерный род занятий  и 1 номер телефона</strong>. </p>
<p>Если же вы собираетесь учавствовать в торгах как исполнитель услуг, вам необходимо максимально полно заполнить весь профиль. От того, насколько качественно и полноценно заполнен ваш профиль, зависит решение покупателя о выборе вас, как исполнителя.</p>
<h3>Визитка</h3>
<p>Во вкладке <strong>«Визитка»</strong> введите ваши данные: фамилию, имя, отчество, загрузите аватар, введите информацию о том, чем вы занимаетесь/должность на работе. Напишите, где проживаете (Страна, регион, город). Укажите обязательно контактный телефон и e-mail. Если есть необходимость, напишите ваш сайт, skype и другую личную информацию. И нажмите кнопку «Сохранить».</p>
<h3>Портфолио</h3>
<p>Добавьте изображения во вкладку <strong>«Портфолио»</strong> при помощи кнопки «Загрузить». Фотографии, картинки и работы по своему содержанию должны соотвествовать представленной в описании деятельности продавца/исполнителя. Также запрещено публиковать фотографии, картинки и работы, противоречащие законам РФ, здравому смыслу, моральным и этическим нормам. Также запрещено использование чужих работ. Пользователь лично несет ответственность за использованные данные.</p>
<h3>Об услуге</h3>
<p>В данном поле опишите как можно подробнее о себе, о своей компании, об услуге/товаре, которую вы оказываете. Напишите сюда ту информацию, которая бы привлекла внимание вашего потенциального клиента, обязательно укажите ваши преимущества перед конкурентами, напишите ваши уникальные предложения, также можете написать тех клиентов, которые у вас уже что-то приобрели/заказали, их отзывы. Информация в данном разделе не должна нарушать законы РФ, должна быть правдивой и соответствовать правилам добросовестной конкуренции. После нажмите кнопку «Сохранить»</p>
<div style="color: #cc0001  ; font-weight: bold;">Утверждения рекламного характера, а также прилагательных в превосходной степени «самый», «полный», «дешевый», «лучший», «единственный» и им подобных, не допускается.</div>

<h3>Категории торгов</h3>
<p> При выборе категорий торгов обязательно проверьте все темы, близкие вашему профилю услуг, так как многие позиции повторяются в разных темах (например: дизайнер-флорист есть в категории «Услуги дизайнеров» и в категории «Все для праздника»). Если вы подпишитесь на определенную позицию только в определенной теме, вы будете получать заявки только от тех клиентов, которые тоже выберут данную позицию, а те, которые выберут похожую категорию в другой теме, пройдут мимо вашего внимания.</p>

<p> Темы показаны, по примеру запроса от лица покупателя.  Вы можете подписаться на 10 тем.</p>
<p>После внесенных изменений, перед тем как покинуть вкладку нажмите кнопку<strong> «Подписаться»</strong>. </p>
<h3>Регионы и города</h3>
<p>А в блоке <strong>«Регионы и города»</strong> выберите те, в которых вы готовы оказывать/продавать свои услуги.</p>

<h3>Ответственность Администрации и пользователя</h3>
<div style="color: #cc0001  ; font-weight: bold;">Обязательно к прочтению:</div>
<p>Сайт «My-Tend.Com» не несет ответственность за указанную пользователем информацию в профиле. Если вы считаете, что какая-либо информация нарушает чьи-либо права, свяжитесь с нами. При поступлении жалобы со стороны других пользователей Администрация сайта имеет право проверить информацию о пользователе всеми доступными способами и при выявлении нарушей заблокировать, либо закрыть доступ для пользования сайтом.</p>

<p>Администрация сайта «My-Tend.Com» не проверяет личности пользователей, а также информацию на ее правдоподобность и соотвествие истине. Поэтому каждый пользователь несет личную ответственность за доверие к той или иной информации, предоставленной другими пользователями сайта.</p>

<p>Все пользователи сайта «My-Tend.Com» регистрируются на данном ресурсе исключительно как физические лица и несут личную ответственность за публикуемую информацию во всех разделах сайта.</p>

<p>Все поля регистрационной формы и вкладки профиля/визитки могут быть изменены пользователем в любое время, кроме города проживания пользователя, указанного при регистрации. Эти данные могут быть изменены только по письменному заявлению пользователя в адрес Администрации сайта с предоставлением паспортных данных.</p>
<p>Заполнение профиля/визитки+нажатие кнопки<strong>«Сохранить»</strong>, означает что:</p>
<p>-пользователь  ознакомился и соглашается со всеми правилами сайта без исключения</p>
<p>-пользователь  согласен с тем что, информация, персональные данные которые он заполняет о себе, будут видны и доступны другим пользователям сети интернет.</p>
<p>-пользователь  обязуется давать реальную информацию о себе, не нарушая права третьих лиц и интеллектуальной собственности.</p>
<p>-пользователь  обязуется и гарантирует что использует сервисы сайта будучи ознакомленым с актуальными статьями законов РФ, в том числе "О рекламе", конкурентного права (антимонопольное право), право интеллектуальной собственности. Пользователи обязуются сообщать Администрации сайта о нарушениях других  пользователей. Выявленное нарушение  может являться поводом для удаления с сайта.</p>
<p>Инструкция и требования могут быть изменены без уведомления пользователя, ознакомление с актуальными версиями пользователь обязуется делать самостоятельно.</p>
Данная инструкция относится к документу <a href="http://my-tend.com/Docs/Rules">«Условия использования сайта»</a> и должна учитываться пользователями сайта в полном объёме.
<div style="color: #cc0001  ; font-weight: bold;">За нарушение пунктов может последовать блокировка и удаление с сайта. </div>

Project/MyTend/MyTend/Views/Docs/AboutSite.cshtml
@{
    ViewBag.Title = "Исполнителям EVENT-индустрии!";
}
<style>
   p {
    border: 1px solid red;
    padding: 10px;
   }
  </style>

<br />




<h3 style="color: #222222;">Стать продавцом услуг на My-Tend.Com</h3>	
<h5 style="color: #222222;">Вы ведущий, DJ, фото/видеограф, менеджер банкетного зала, 
event-агентво, оказываете услуги кейтеринга, транспортные услуги и не только...</h5> 
   
   <h5></h5>


<br /><br />
		 <div class="row">
            <div class="col-md-2"><img src="~/Content/images/plakat.png" width="100" height="100" /></div>
            <div class="col-md-8" style="line-height:20px">
                <div style="font-weight: bold; font-size: 17px;">Учавствуйте в конкурсных торгах на право исполнения Event-услуги! 
				</div>
				<br />
                <div style="font-size: 14px;">
                Принимайте участие в конкурсах на право оказания услуг в сфере праздничных событий, по принципу тендера.<br />
   Сайт будет присылать вам заявки от будущих клиентов с ферах деятельности и городах которые вы укажете в личной подписке.<br />
   В заявках будут указаны - суть будущего события, бюджет, город, дата, и прочие важные детали,
   по ним Вы сможете решить - интересно ли Вам соревноваться за этот  заказ.<br />
   Наблюдайте, как  предлагают свои услуги Ваши коллеги-конкуренты,  предлагайте более выгодные предложения. Побеждайте!

                </div>
 </div> </div>
 <br />

		 <div class="row">
            <div class="col-md-2"><img src="~/Content/images/filosof.png" width="100" height="100" /></div>
            <div class="col-md-8" style="line-height:20px">
                <div style="font-weight: bold; font-size: 17px;">Наша философия, Ваши приемущества и возможности.! 
				</div>
	            <div style="font-size: 14px;">
		             <br/>
		            <li >
			            У всех всегда должет быть выбор. Всегда и везде. Если Вы считаете, что должны выбрать именно Вас, будьте - конкурентоспособным,
			            интересным исполнителем, предлагающим хорошую услугу за вменяемую цену.
		            </li >
		            <li >
			            На Май-Тенд нет VIP, PRO и прочих "блатных" аккаунтов обладающих "суперспособностями" и прочими преимуществами.
		            </li >
		            <li >
			            Мы за здоровую конкуренцию в сфере Evetnt, без неоправданного завышения цен и прочего пафоса. Во преки мнению это не аукцион "кто дешевле" а поиск
			            лучшего предложения по формуле " цена/качество" по мнению заказчика.
		            </li>
		            <li >
			            Все просто - тот, чьё предложение было написано первее - будет первым. Кто написал вторым, будет вторым, и.т.д.
			            Ваше предложение не спустится вниз и не станет незаметным из за того, что кто-то написал тоже.
		            </li >

		            <li >До начала сентября сервис будет бесплатным.<br/> Пользователи, которые будут принимать
			            активное участие в жизни сайта, предложат сотрудничество, бартер и прочие предложения
			            по улучшению и развитию сайта, будут размещаться бесплатно - всегда.
		            </li>



	            </div> 
	            </div>
</div> 
@if (ViewBag.IsAuth == true)
{
	<div class="row" style="padding-top: 20px;">
		<div class="col-lg-12">
			<div class="text-center">
				<input id="isAgree" type="checkbox"/> Принимаю все условия афёрты
			</div>
		</div>
	</div>
	
	<div class="row" >

		<div class="col-lg-12 text-center">
			<br />
			<div>
				Пока что, бесплатно!	
			</div>
			<div class="btn btn-warning disabled" id="setPayed">
				Стать продавцом услуг
			</div>
			
		</div>
	</div>
	<script>
	    $(document).ready(function() {
		    $("#isAgree").change(function() {
			    if (this.checked) {
				    console.log(1);
				    $('#setPayed').removeClass('disabled');
			    } else {
				    console.log(2);
				    $('#setPayed').addClass('disabled');
			    }
		    });

		    $('#setPayed').on('click',
			    function() {
				    var agree = $("#isAgree").prop('checked');
				    
				    if (agree) {
					    var url = window.location.protocol + '//'+ window.location.host + '/Pay/SetPayed';
					    window.location = url;
				    }
			    });
	    })
	</script>
}


			

Project/MyTend/MyTend/Views/Docs/AboutWork.cshtml
@{
    ViewBag.Title = "	Заказать ведущего, тамаду. банкетный зал, фотографа на конкурсной основе";
}
<div class="form-group" style="text-align: center">
    <h2><div style="color: #1db7de;">У Вас намечается праздничное событие и Вы задумались как и где его организовать, чем угощать и развлекать гостей?</h2>
	<h3><div style="color: #222222;">Устройте конкурс на право исполнения у	Event-услуг на Вашем празднике!</h3>
	</div>
<div class="row aw-block">
    <div class="col-md-3">
        <div class="aw-cont">
            <img src="~/Content/images/inf1.svg" />
        </div>
        <div class="aw-text">
            <div class="abw-head">
                <strong>Заполняете  заявку </strong>
            </div>
            <div class="abw-text">
                Регистрируетесь на сайте.Это займет меньше минуты. Подробно описываете Ваше событие, указываете местоположение, время, количество гостей  и примерный бюджет который вы планируете потратить.
                <br />
                <a class="btn btn-custom-red header-btn" href="~/Tender/Index"><strong>Оставьте заявку <br>исполнителям</strong></a>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="aw-cont">
            <img src="~/Content/images/inf2.svg" />
        </div>
        <div class="aw-text">
            <div class="abw-head">
                <strong>Исполнители предлагают выгодные условия для исполнения Вашего заказа </strong>
            </div>
            <div class="abw-text">
                После того как вы отправили заявку, система приглашает Исполнителей принять участие в конкурсе/торге по Вашей  заявке. Исполнители  которые подписаны на услугу и город которые вы указали - делают Вам предложения на конкурсной основе, соревнуясь между собой, тем что  предлагают для Вас выгодные условия и возможно бонусы.
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="aw-cont">
            <img src="~/Content/images/inf3.svg" />
        </div>
        <div class="aw-text">
            <div class="abw-head">
                <strong>    Сравниваете все предложения и выбираете самое выгодное</strong>
            </div>
            <div class="abw-text">
                В течении нескольких дней следите за тем как поступают предложения  от продавцов. При необходимости задаете им вопросы.
                Дождавшись максимальное количество предложений, Вы - выбираете самое выгодное и нажимаете кнопку "ВЫБРАТЬ ПОБЕДИТЕЛЕМ".
                <br />
                <a class="btn btn-custom-aqua header-btn" href="~/Tender/Index"><strong>Проверить <br>предложения <br>от исполнителей</strong></a>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="aw-cont">
            <img src="~/Content/images/inf4.svg" />
        </div>
        <div class="aw-text">
            <div class="abw-head">
                <strong>Созваниваетесь, встречаетесь, заключаете договор, ждете праздник!</strong>
            </div>
            <div class="abw-text">
                Договариваетесь о сделке по телефону, указанному в визитке победителя Вашей заявки. Совершаете сделку при личной встрече, на условиях которые нужный исполнитель предложил Вам на нашем сайте, ждете праздника, веселитесь на нем!
            </div>
        </div>
    </div>
</div>
<hr>
<h3><div style="color: #873d83;"><div class="form-group" style="text-align: center">В ЧЕМ ОЧЕВИДНАЯ ВЫГОДА ИСПОЛЬЗОВАНИЯ САЙТА MY-TEND.COM</h3>
<h5><div style="color: #222222;">На нашем сайте НЕТ готовых объявлений, списков, рейтингов! Только конкретные предложения  под конкретный заказ!Вы лишь выбираете самое выгодное!</h5>
 <hr>
<h5><div style="color: #222222;">Вы не только  не переплачиваете общаясь напрямую с нужным исполнителем без посредников но и с большей вероятностью получаете скидки или бонусы, так как продажа на виду у коллег конкурентов диктует быть лучше и выгоднее.</h5>
 <hr>
<h5><div style="color: #222222;"> Только реальные и актуальные предложения под условия Вашего заказа! Вы не тратите время на общение с исполнителями которые уже заняты или им "мало денег", не надо обзванивать десятки объявлений объясняя одно и тоже.</h5>
 <hr>
<h5><div style="color: #222222;"> Конкурентная форма выбора исполнителя дает Вам хорошие предложения услуг и сервиса за вменяемые деньги.</h5>
 <hr>
<div class="form-group" style="text-align: center">
<a href="https://my-tend.com/Docs/AboutWork2" target="_blank"><strong>Если Вы исполнитель услуг или как выйграть заказ</strong></a></div>
<div class="row">
    <div class="col-md-12">
        <div style="text-align: center;">
            @Html.ActionLink("Перейдите к регистрации", "Registration", "Account", null, new { @class = "btn btn-custom-red", @style = "  margin-top: 10px;" })
        </div>
    </div>
</div>

Project/MyTend/MyTend/Views/Docs/AboutWork2.cshtml
@{
    ViewBag.Title = "	Заказать ведущего, тамаду. банкетный зал, фотографа на конкурсной основе";
}
<div class="form-group" style="text-align: center">
    <img src="~/Content/images/aboutWork.svg" style="width: 60%" />
    <h1><div style="color: #1db7de;"> Вы ведущий, DJ, менеджер банкетного зала, артист, декоратор и.т.д?</h1>
    <h3>Принимайте активное участие в конкурсах (аукционных-торгах) на право оказания Event-услуг для заказчика!</h3>
		</div>
<div class="row aw-block">
    <div class="col-md-3">
        <div class="aw-cont">
            <img src="~/Content/images/inf-2-1.svg" />
        </div>
        <div class="aw-text">
            <div class="abw-head">
                <strong>Регистрируетесь на сайте </strong>
            </div>
            <div class="abw-text">
                Подробно заполняете все пункты визитки: портфолио, об услуге, контактные данные. Ваша визитка - Ваше лицо во время проведения конкурса (торга) и выбирать исполнителя могут исходя из данных в визитке!               <br />
                </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="aw-cont">
            <img src="~/Content/images/inf-2-2.svg" />
        </div>
        <div class="aw-text">
            <div class="abw-head">
                <strong>Оформляете подписку и оплачиваете доступ к участию в конкурсных торгах.</strong>
            </div>
            <div class="abw-text">
                Что бы система присылала приглашения на участие в конкурсных торгах только по сфере Вашей деятельности, Вам необходимо "рассказать" ей какие именно услуги Вы оказываете и в каких регионах/городах. Далее, оплачиваете "торговый взнос" 1000 рублей  за 2 календарных месяца. После этого в меню откроются списки заявок от заказчиков а так же система  даст право принимать участие в конкурсных-торгах в роли "продавца услуг" (меню "Редактировать визитку".
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="aw-cont">
            <img src="~/Content/images/inf-2-3.svg" />
        </div>
        <div class="aw-text">
            <div class="abw-head">
                <strong> Участие в конкурсных торгах"</strong>
            </div>
            <div class="abw-text">
              Получив приглашение ( по e-mail) на участие в конкурсных торгах, Вы решаете, желаете ли вы "соревноваться за этот заказ". Исходя из условий в  заявке и предложений от конкурентов, делаете заказчику свое предложение с указанием всех ваших преимуществ! При необходимости, ознакомившись с  предложениями коллег-конкурентов, Вы можете сделать ещё одно предложение.</div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="aw-cont">
            <img src="~/Content/images/inf-2-4.svg" />
        </div>
        <div class="aw-text">
            <div class="abw-head">
                <strong>У всех равные шансы на победу в торгах!</strong>
            </div>
            <div class="abw-text">
               У всех исполнителей услуг одинаковые шансы и возможности. Ваш успех зависит от того, как быстро вы ответили, насколько интересно предлагаете, как выгодно отличаетесь от коллег-конкурентов. Если ваше предложение оказывается самым выгодным, заказчик объявляет вас победителем и связывается с вами для обсуждения/совершения возможной сделки.
            </div>
        </div>
    </div>
</div>
<hr>
<h3><div style="color: #873d83;"><div class="form-group" style="text-align: center">В ЧЕМ ОЧЕВИДНАЯ ВЫГОДА ИСПОЛЬЗОВАНИЯ САЙТА MY-TEND.COM?</h3>
<hr>
 <h5>У нас нет готовых списков объявлений,  которые ждут пока их заметит потенциальный заказчик среди одинаково похожих! </h5>
<h5>И поэтому  ТОЛЬКО предложения под конкретный заказ!
Наш сайт дает вам возможность не потеряться среди миллионов одинаковых объявлений а показать самые лучшие стороны Вас и вашей услуги во время тендеров  от юбиляров, молодожен, сотрудников компаний.</h5>
<hr> 
<h5>Зная условия заявки от заказчиков и прочитав предложения от коллег-конкурентов на этот заказ, Вы решаете нужен Вам этот заказ или нет. </h5>
<hr>
<h5>Это может помочь Вам более эффективно вести переговоры с потенциальным заказчиком и сделать для него предложение, от которого он не сможет отказаться!</h5>
<hr>
<h5>Вы оплачиваете 1000 рублей за 2 месяца доступа к заявкам и ни копейки больше!   </h5>

<hr>
<div class="form-group" style="text-align: center">
<a href="https://my-tend.com/Docs/AboutWork" target="_blank"><strong>Если у Вас скоро праздник и Вы желаете заказать услугу выбрав исполнителя усллуги</strong></a></div>
<div class="row">
    <div class="col-md-12">
        <div style="text-align: center;">
            @Html.ActionLink("Перейдите к регистрации", "Registration", "Account", null, new { @class = "btn btn-custom-red", @style = "  margin-top: 10px;" })
        </div>
    </div>
</div>

Project/MyTend/MyTend/Views/Docs/FAQ.cshtml
@{
    ViewBag.Title = "Добро пожаловать на MY-TEND.COM";
}
<h4 style="color: #222222;"><strong>Правила для продавцов / исполнителей сайта MY-TEND.COM</strong></h4>	
<h5 style="color: #dd0b29;">За нарушение правил сайта - блокировка до выяснения причин со стороны пользователя.</h5>
<hr>
<div class="col-md-8" style="line-height:30px">
<h5 style="color: #777777;">
<ol>
<li>Свод данных правил принимается пользователем без исключения и является дополнением к <a href="~/Docs/Rules">Условиям использования сайта</a> </li><br />
<li>Участие в конкурсных торгах без заполненного профиля визитки, номера телефона, фото-аватара запрещена.</li><br />
<li>Фото-аватар визитки, допускается только с личным изображением, не допустимо использовать чужие фото, логотипы,
 фото животных и прочих героев интернета.</li><br />
<li>Номер телефона должен быть актуальным, на момент участия в конкурсах+1 месяц с крайнего участия.</li><br />
<li>Исполнитель должен предоставить услугу заказчику, в случае его победы, на условиях которые он написал во время конкурса.</li><br />
<li>Сайт не является организатором сделки, покупателем, продавцом, посредником, агентом или представителем какого-либо
 Пользователя и/или иным заинтересованным лицом в отношении предлагаемой/заключаемой между Пользователями сделки. Все совершаемые 
благодаря размещению информации на Сайте сделки между Пользователями заключаются и исполняются без прямого или косвенного участия Сайта.</li><br />
<li>Во время конкурса допускаются сообщения / предложения, исключительно по теме заказа. Флуд, личные мнения, выяс</li><br />
<li></li><br />
<li></li><br />


</ol>
</h5>
 </div>

 
 <h5>Сайт не является  гарантом сделок</h5>

Project/MyTend/MyTend/Views/Docs/Index.cshtml
@{
    ViewBag.Title = "Документы";
}

<h2>Документы</h2>

<p>
    @Html.ActionLink("Договор оказания платных услуг", "Oferta", "Docs")
</p>
<p>
    @Html.ActionLink("Условия использования сайта", "Rules", "Docs")
</p>
<p>
    @Html.ActionLink("Правила заполнения профиля", "AboutProfile", "Docs")
</p>
<p>
    @Html.ActionLink("Инструкция заполнения заявок", "Instruction", "Docs")
</p>
<p>
    @Html.ActionLink("Как это работает", "AboutWork", "Docs")
</p>

Project/MyTend/MyTend/Views/Docs/Torgs.cshtml
@{
    ViewBag.Title = "Исполнителям EVENT-индустрии!";
}
<style>
   p {
    border: 1px solid red;
    padding: 10px;
   }
  </style>

<br />




<h1 style="color: #000000;"><STRONG> Стать продавцом услуг на My-Tend.Com</STRONG></h1>	
<h5 style="color: #777777;">Конкуренция, наполненная духом азарта!</h5> 
   
<link rel="canonical" href="https://my-tend.com/"/>
<br /><br />
		 <div class="row">
            <div class="col-md-2"><img src="~/Content/images/torgash.svg" width="100" height="100" /></div>
            <div class="col-md-8" style="line-height:20px">
               
	            <div style="font-size: 15px;">
		            <i>
			            <STRONG>
				            Вы ведущий / тамада, DJ, фото/видеограф, менеджер банкетного зала / кафе,
				            event-агентво, артист оригинального жанра, оказываете услуги кейтеринга, транспортные услуги и не только...
			            </STRONG>
		            </i>
		            <br/>
		            <br/>
		            Принимайте участие в конкурсных торгах на право оказания услуг в сфере праздничных событий по принципу открытого тендера.<br/>
		            Сайт будет присылать вам заявки от будущих клиентов в сферах деятельности и городах, которые вы укажете в личной подписке.<br/><br/>
		            В заявках будут указаны:
		            <ul>
			            <li >название события и текст заявки</li >
			            <li >дата / время </li >
			            <li >бюджет</li >
			            <li >город</li >
			            <li >колличество гостей</li >
			            <li >фотографии ( по необходимости )</li >
			            <li >дата начала и финала конкурса</li >    
		            </ul>
		            <br/>
		            Ознакомившись с этой информацией, Вы решаете - принимать участие или нет.<br/>
		            Наблюдайте, как предлагают свои услуги Ваши коллеги-конкуренты. Предлагайте более выгодные предложения. Побеждайте!

	            </div>
 </div> </div>
@if (ViewBag.IsAuth == true)
{
	<div class="row" style="padding-top: 20px;">
		<div class="col-lg-12">
		   <br/>   <br/>
			<div class="text-center">
				<input id="isAgree" type="checkbox"/>Я принимаю правила участия в конкурсных торгах и желаю получить статус продавца услуг.
			</div>
		</div>
	</div>
	
	<div class="row" >

		<div class="col-lg-12 text-center">
		
			<div>
				Пока что, бесплатно!	
			</div>
			<div class="btn btn-warning disabled" id="setPayed">
				Стать продавцом услуг
			</div>
			
		</div>
	</div>
	<script>
	    $(document).ready(function() {
		    $("#isAgree").change(function() {
			    if (this.checked) {
				    console.log(1);
				    $('#setPayed').removeClass('disabled');
			    } else {
				    console.log(2);
				    $('#setPayed').addClass('disabled');
			    }
		    });

		    $('#setPayed').on('click',
			    function() {
				    var agree = $("#isAgree").prop('checked');
				    
				    if (agree) {
					    var url = window.location.protocol + '//'+ window.location.host + '/Pay/SetPayed';
					    window.location = url;
				    }
			    });
	    })
	</script>
}

 <br />