Project/MyTend/MyTend/Models/Tender/ActiveTenderListModel.cs
namespace MyTend.Models
{
    using MyTend.Entites;
    using MyTend.Services.Common;
    using MyTender.Security;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;

    public class ActiveTenderListModel
    {
        public List<Tender> OpenTenders { get; set; }

        public List<Tender> CloseTenders { get; set; }

        private AuthService Auth { get; set; }

        private RegionFilterService RegionFilter { get; set; }

        private TenderFilterService TendersFilter { get; set; }

        private List<Tender> MyActivetenders { get; set; }

        public ActiveTenderListModel()
        {
            var service = new TenderService().GetList();

            this.OpenTenders = new List<Tender>();
            this.CloseTenders = new List<Tender>();

            this.OpenTenders.AddRange(service.Open);
            this.CloseTenders.AddRange(service.Close);
        }
    }
}

Project/MyTend/MyTend/Models/Tender/CloseTenderModel.cs
using MyTend.Entites;
using MyTender.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MyTend.Models
{
    public class CloseTenderModel
    {
        public Tender Tender { get; set; }

        public UserSystem Winner { get; set; }

        private AuthService Auth { get; set; }

        private FriendModel Friend { get; set; }

        public CloseTenderModel(int userId, int tenderId)
        {
            this.Winner = UserSystem.GetById(userId);
            this.Tender = Tender.GetById(tenderId);
            this.Friend = new FriendModel(this.Winner.Login);
        }

        public void Cancel()
        {
            if (this.Winner.Id == this.Tender.User.Id)
            {
                this.Tender.Cancel();
            }
        }

        public bool Close()
        {
            this.Tender.SetWinner(this.Winner);

            this.Friend.Save();

            return true;
        }
    }
}

Project/MyTend/MyTend/Models/Tender/CreateTenderModel.cs
namespace MyTend.Models
{
    using System;
    using System.Collections.Generic;
    using System.Configuration;
    using System.Linq;
    using System.Web;
    using MyTend.Entites;
    using MyTend.Services;
    using MyTend.Services.File;
    using MyTender.Security;
    using NHibernate.Criterion;

    public class CreateTenderModel : Tender
    {
        public string AllowWrite { get; set; }

        public string ActiveTime { get; set; }

        public string CountryId { get; set; }

        public string RegionId { get; set; }

        public string CityId { get; set; }

        //public CloseTenderTimeEnum CloseTime { get; set; }

        public List<TenderTheme> ListThemes { get; set; }

        public int ThemeId { get; set; }

        public int TitleId { get; set; }

        //public string IconTheme { get; set; }

        public string TenderType { get; set; }
        
        public List<Country> ListCountrys { get; set; }

        public List<Region> ListRegions { get; set; }

        public HttpPostedFileBase[] ListFiles { get; set; }
        public HttpPostedFileBase[] qqfile { get; set; }
        
        private bool IsSub { get; set; }

        public CreateTenderModel()
        {

        }

        public CreateTenderModel(int themeId)
        {
            var theme = TenderTheme.FindAll()
                .FirstOrDefault(x => x.Id == themeId);

            if (theme == null)
            {
                throw new Exception("Неизвестный конкурсный торг.");
            }

            var listSubThemes = TenderTheme.FindAll(Expression.Eq("Theme", theme.Theme))
                //.Where(x => x.Theme == theme.Theme)
                .OrderBy(x => x.NomberInList)
                .ToList();

            this.Theme = theme;

            this.ListThemes = listSubThemes;
            //this.IconTheme = theme.ImageName;
            this.ListCountrys = RegionService.CountryAll();
            this.ListRegions = RegionService.RegionAll();
        }

        public bool IsValid()
        {
            var tender = this.GetObj();

            var isValid = tender.IsValid();

            if (!isValid) 
            {
                this.Errors = tender.Errors;
            }

            var count = this.GetCountTendersToday(tender.User);
            var maxCount = 0;

            if (this.IsSub)
            {
                maxCount = int.Parse(ConfigurationManager.AppSettings["MaxTendersSub"]);
            }
            else
            {
                maxCount = int.Parse(ConfigurationManager.AppSettings["MaxTenders"]);
            }

            if (count >= maxCount)
            {
                this.Errors.Add(string.Format(ConfigurationManager.AppSettings["MaxTenderMessage"], maxCount));
                isValid = false;
            }

            var theme = TenderTheme.FindAll()
                .FirstOrDefault(x => x.Id == this.ThemeId);

            if (theme == null)
            {
                throw new Exception("Неизвестный конкурсный торг.");
            }

            var listSubThemes = TenderTheme.FindAll(Expression.Eq("Theme", theme.Theme))
                //.Where(x => x.Theme == theme.Theme)
                .OrderBy(x => x.NomberInList)
                .ToList();

            this.Theme = theme;

            this.ListThemes = listSubThemes;
            //this.IconTheme = theme.ImageName;
            this.ListCountrys = RegionService.CountryAll();

            return isValid;
        }

        private int GetCountTendersToday(UserSystem user)
        {
            var begin = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day);
            var end = begin.AddHours(23).AddMinutes(59).AddSeconds(59);

            var count = Tender.FindAll(Expression.Eq("User", user))
                //.Where(x => x.User.Id == user.Id)
                .Where(x => x.CreatedDateTime >= begin && x.CreatedDateTime <= end)
                .Count();

            return count;
        }

        public void Save(bool isSub)
        {
            this.IsSub = isSub;

            var obj = this.GetObj();

            obj.Create();

            this.SaveFiles(obj);

            this.Id = obj.Id;
        }

        private void SaveFiles(Tender tender)
        {
            if (this.ListFiles != null && this.ListFiles.Length > 0)
            {
                var service = new FileControllerService();

                service.SaveFileTender(this.ListFiles, tender);
            }
        }

        private Tender GetObj()
        {
            var newTender = new Tender()
            {
                IsOpen = this.IsOpen,
                AllowWriteMe = this.AllowWriteMe,
                City = this.City,
                Cost = this.Cost,
                DateEnd = this.DateEnd,
                Message = this.Message,
                Region = this.Region,
                Theme = this.Theme,
                EventDay = this.EventDay,
                EventTime = this.EventTime,
                Title = this.Title,
                User = this.User,
                CountGuests = this.CountGuests
            };

            switch (this.ActiveTime)
            {
                case "3 дня":
                    newTender.DateEnd = DateTime.Now.AddDays(3);
                    break;
                case "7 дней":
                    newTender.DateEnd = DateTime.Now.AddDays(7);
                    break;
                case "14 дней":
                    newTender.DateEnd = DateTime.Now.AddDays(14);
                    break;
                case "21 день":
                    newTender.DateEnd = DateTime.Now.AddDays(21);
                    break;
            }

            switch (this.TenderType)
            {
                case "Открытые торги":
                    newTender.IsOpen = true;
                    break;
                case "Закрытые торги":
                    newTender.IsOpen = false;
                    break;
            }

            var theme = TenderTheme.GetById(this.TitleId);

            if (theme == null)
            {
                //throw new Exception("Не известная тема тендера");
            }

            newTender.Theme = theme;

            var region = Region.FindFirst(Expression.Eq("Name", this.RegionId));
                //.FirstOrDefault(x => x.Name == this.RegionId);

            if (region == null)
            {
                //throw new Exception("Не известный региион");
            }

            var city = City.FindAll(Expression.Eq("Name", this.CityId))
                .FirstOrDefault(x => x.Name == this.CityId && 
                    x.Region.Id == region.Id);

            if (city == null)
            {
                //throw new Exception("Не известный город");
            }

            newTender.Region = region;
            newTender.City = city;

            var authService = new AuthService();

            newTender.User = authService.User;

            switch (this.AllowWrite)
            {
                case "on":
                    newTender.AllowWriteMe = true;
                    break;
                default:
                    newTender.AllowWriteMe = false;
                    break;
            }

            return newTender;
        }
    }
}

Project/MyTend/MyTend/Controllers/CardController.cs
namespace MyTend.Controllers
{
    using MyTend.Models;
    using MyTender.Security;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;

    public class CardController : BaseController
    {
        // GET: Card
        public ActionResult Index()
        {
            var model = new ListContactModel();

            return View(model);
        }

        [HttpPost]
        public ActionResult Add(string login)
        {
            var model = new FriendModel(login);

            if (model.IsValid())
            {
                model.Save();

                return JsonSuccess();
            }

            return JsonFailur(model.Errors);
        }

        [HttpPost]
        public ActionResult Remove(string login)
        {
            var model = new FriendModel(login);

            if (model.IsValid())
            {
                model.Revome();

                return JsonSuccess();
            }

            return JsonFailur(model.Errors);
        }

        [HttpGet]
        public ActionResult Write(string toUser)
        {
            var model = new WriteMessageModel(toUser);

            return View(model);
        }

        [HttpPost]
        public ActionResult Write(WriteMessageModel model)
        {
            if (model.IsValid())
            {
                model.Save();
            }

            return RedirectToAction("Write", new { @toUser = model.ToUserLogin });
        }
    }
}

Project/MyTend/MyTend/Controllers/TenderController.cs
namespace MyTend.Controllers
{
    using MyTend.Attributes;
    using MyTend.Entites;
    using MyTend.Models;
    using MyTend.Services.EmailService;
    using MyTender.Core;
    using MyTender.Security;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using MyTend.Models;

    public class TenderController : BaseController
    {
        private string tempString = string.Empty;

        /// <summary>
        /// Выбор создания тендера
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            var model = new ListThemeTenderModel();

            return View(model);
        }

        /// <summary>
        /// Список тендеров
        /// </summary>
        /// <returns></returns>
        [BanResource]
        [SmsActivation]
        [OnlySub]
        public ActionResult List()
        {
            var model = new ActiveTenderListModel();

            return View(model);
        }

        public ActionResult Hide(int id)
        {
            var exist = TenderHide
                .FindAll()
                .Where(x => x.User.Id == this.Auth.User.Id)
                .FirstOrDefault(x => x.Tender.Id == id);

            if (exist == null)
            {
                var hiden = new TenderHide()
                {
                    User = this.Auth.User,
                    Tender = Tender.GetById(id)
                };

                hiden.Save();
            }

            return JsonSuccess();
        }

        /// <summary>
        /// Создать тенедер
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [BanResource]
        [SmsActivation]
        public ActionResult Create(int id)
        {
            var model = new CreateTenderModel(id);

            return View(model);
        }

        /// <summary>
        /// Создать тенедер
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [ValidateInput(false)]
        [BanResource]
        [SmsActivation]
        public ActionResult Create(CreateTenderModel model)
        {
            if (this.Auth.User == null)
            {
                return RedirectToAction("Registration", "Account");
            }

            if (model.IsValid())
            {
                var isSub = this.Auth.User.SubToDate >= DateTime.Now;

                model.Save(true);

                this.tempString = model.Title;
                
                try
                {
                    var service = new EmailService(this.Auth.User.Email);
                    service.Create(
                        Auth.User.FullName,
                        model.Title,
                        model.Id);
                }
                catch(Exception e)
                {
                }
                
                return RedirectToAction("Created", new { id = model.Id });
            }

            var temModel = new CreateTenderModel(model.ThemeId);
            model.ListRegions = temModel.ListRegions;

            return View(model);
        }

        public ActionResult Created(int id)
        {
            var tender = new TenderService().GetTender(id);

            return View(tender);
        }

        public ActionResult UpdateSubs(FilterContext context)
        {
            var model = new ListTendersModel(context);

            return View(model);
        }

        /// <summary>
        /// Активные тендеры
        /// </summary>
        /// <returns></returns>
        [BanResource]
        [SmsActivation]
        [OnlySub]
        public ActionResult Active(FilterContext context) 
        {
            var model = new ListTendersModel(context);

            return View(model);
        }
        
        /// <summary>
        /// Мои тендеры
        /// </summary>
        /// <returns></returns>
        public ActionResult My()
        {
            var model = new MyTendersModel();

            return View(model);
        }
        
        [BanResource]
        [SmsActivation]
        [OnlySub]
        public ActionResult Winner()
        {
            var model = new WinnerTenderModel();

            model.Load();

            return View(model);
        }

        /// <summary>
        /// Подробно
        /// </summary>
        /// <param name="id">Id тендера</param>
        /// <returns></returns>
        [SmsActivation]
        public ActionResult Details(int id)
        {
            var model = new TenderDetailsModel(this.Auth, id);

            ViewBag.StandatdGallery = true;
                
            return View(model);
        }

        public ActionResult SelectedWinner(int id)
        {
            var tender = new TenderService().GetTender(id);

            return View(tender);
        }

        public ActionResult SelectWinner(int userId, int tenderId)
        {
            try
            {
                var model = new CloseTenderModel(userId, tenderId);
                model.Close();

                try
                {
                    var service = new EmailService(model.Winner.Email);
                    service.Winner(
                        tenderId.ToString(), 
                        model.Winner.FullName, 
                        model.Tender.Title,
                        model.Tender.User.Login,
                        model.Tender.User.Phone);
                }
                catch
                { }
            }
            catch(Exception ex)
            {
                return JsonFailur(ex.Message);
            }

            return JsonSuccess();
        }

        public ActionResult CancelTender(int id)
        {
            var model = new CloseTenderModel(this.Auth.User.Id, id);
            model.Cancel();

            return RedirectToAction("My");
        }

        [HttpPost]
        [BanResource]
        public ActionResult AddComment(TenderMessageModel model)
        {
            try
            {
                if (model.IsValid())
                {
                    model.Save();
                    
                    return JsonSuccess();
                }
            }
            catch
            { }

            return JsonFailur(model);
        }

        public ActionResult Map()
        {
            var themes = new Dictionary<string, List<TenderTheme>>();

            var all = TenderTheme.FindAll()
                .OrderBy(x => x.Theme)
                .ToList();

            all.ForEach(x => {
                if (!themes.Keys.Contains(x.Theme))
                {
                    themes.Add(x.Theme, new List<TenderTheme>());
                }

                themes[x.Theme].Add(x);
            });

            return View(themes);
        }
    }
}

Project/MyTend/MyTend/Views/Tender/Active.cshtml
@model MyTend.Models.ListTendersModel

@{
    ViewBag.Title = "Заявки от заказчиков/покупателей";
}
<div class="form-group" style="text-align: center">
<h5 style="color: #333333;">
    Уточните: сферу Вашу сферу деятельности, города в которых можете брать заказы.   <br />
    Мы пришлем письмо на электронную почту и отобразим в этом меню
 ,
    когда появятся новые заявки </h5>
</div>
<div style="padding-top: 20px;">
	@RenderPage("Common/Search.cshtml", Model)
</div>


<h1 style="color: #000000;"><STRONG> Заявки от Заказчиков</STRONG></h1>

<h5 style="color: #777777;">
 Если Вы откликнитесь  предложением для заказчика, заявка перейдет в меню <a href="/tender/Active">Мои предложения Заказчикам</a>, где Вы сможете следить за ходом аукционного-торга.

 </h5>
<hr>
<div class="tabs">
     
    <div class="tab-content">
        <div class="tab-pane active" id="tab5-1">
            @if (Model.Tenders.Count > 0)
            {
                foreach (var item in Model.Tenders)
                {
                    <div class="row" id="tenderrow-@item.Id">
                        <div class="col-lg-2 text-center">
                            <a href="~/Tender/Details?id=@item.Id">
                                @if (item.User.Avatar != null)
                                {
                                    <div>
                                        <img src="~/image/get/@item.User.Avatar.Id" width="100" height="100" class="img-circle" />
                                    </div>
                                }
                                else
                                {
                                    <div>
                                        <img src="~/image/get/0" width="100" height="100" class="img-circle" />
                                    </div>
                                }
                                
                            </a>
                        </div>
                        <div class="col-lg-10">
                            <table style="width: 100%">
                                <tr>
                                    <td width="5%" style="text-align: right;">
                                        <strong></strong>
                                    </td>
                                    <td style="padding-left: 10px;">
                                        <h4> @Html.ActionLink(item.Title, "Details", "Tender", new { id = item.Id }, null) </h4>
                                    </td>
                                </tr>
                                <tr>
                                    <td width="5%" style="text-align: right;">
                                        <strong></strong>
                                    </td>
                                    <td style="padding-left: 10px;">
                                        @if (item.Cost == 0)
                                        {
                                            @:<div><p style="word-wrap: break-word; font-size: 17px;">Договорная</div>
                                    }
                                        else
                                        {
                                            @:<div><p style="font-size:17px">@item.Cost.ToString("0.00") руб.</p></div>
                                    }
                                    </td>
                                </tr>
                                <tr>
                                    <td width="5%" style="text-align: right;">
                                        <strong></strong>
                                    </td>
                                    <td style="padding-left: 10px; line-height: 18px;">
                                        <div>@string.Format("{0}", item.Theme.Title)</div>
                                        <div>@string.Format("{0} / {1}", item.Region.Name, item.City.Name) </div>
                                        <div>@string.Format("Рассмотрение предложений: c " + item.CreatedDateTime.ToString("dd.MM.yyyy") + " до " + item.DateEnd.ToString("dd.MM.yyyy"))</div>
                                    </td>
                                </tr>

                                <tr>
                                    <td width="5%" style="text-align: right;">
                                        <strong></strong>
                                    </td>
                                    <td style="padding-left: 10px; text-align: right;">
                                        <a href="#" style="color: #b0b0b0;" onclick="hideTender(@item.Id)"><i class="glyphicon glyphicon-remove" style="color: #b0b0b0;"></i>Удалить</a>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                }
            }
            else
            {
			<p class="bg-warning">
                
                <h5 style="color: #777777;">
				 <img src="~/Content/images/light-bulb.png"width="18" height="18" />Заявок по условиям выбранных услуг и городов, пока не поступало, рекомендуем проверить позже!<br /><br />
                    В случае если кто то разместит заявку в категории ваших услуг и городе, Робот-Тендер оповестит
					и пригласит Вас ознакомиться с заявками, по электронной почте.<br /><br />
					Так же рекомендуем проверять наличие новых заявок самостоятельно, в этом пункте меню. 
                </h5>
				
			
           
                
				</p>
            }

        </div>
	 
    </div>
</div>

Project/MyTend/MyTend/Views/Tender/Closed.cshtml
@model MyTend.Models.ActiveTenderListModel

@{
    ViewBag.Title = "Закрытые заявки/торги";
}

<table class="table table-striped">
    <tr>
        <th>
            Название заявки/торгов
        </th>

        <th style="text-align: center">
            Тема/категория
        </th>

        <th style="text-align: center">
            Регион/Город исполнения заявки
        </th>

        <th style="text-align: center">
            Победитель 
        </th>
    </tr>

    @if (Model.CloseTenders.Count == 0)
    {
        <tr>
            <td colspan="4" style="text-align: center;">
                нет активных торгов
            </td>
        </tr>
    }

    @foreach (var item in Model.CloseTenders)
    {
        <div class="row" id="tenderrow-@item.Id">
            <div class="col-lg-1">
                <a href="~/Tender/Details?id=@item.Id">
                    <img src="~/Content/images/kats/@item.Theme.ImageName" width="90" height="100" />
                </a>
            </div>
            <div class="col-lg-11">
                <table style="width: 100%">
                    <tr>
                        <td width="20%" style="text-align: right;">
                            <strong></strong>
                        </td>
                        <td style="padding-left: 10px;">
                            <h4> @Html.ActionLink(item.Title, "Details", "Tender", new { id = item.Id }, null) </h4>
                        </td>
                    </tr>
                    <tr>
                        <td width="20%" style="text-align: right;">
                            <strong></strong>
                        </td>
                        <td style="padding-left: 10px;">
                            @if (item.Cost == 0)
                            {
                                @:<div><p style="word-wrap: break-word; font-size: 17px;">Договорная</div>
                                    }
                            else
                            {
                                @:<div><p style="font-size:17px">@item.Cost.ToString("0.00") руб.</p></div>
                                    }
                        </td>
                    </tr>
                    <tr>
                        <td width="20%" style="text-align: right;">
                            <strong></strong>
                        </td>
                        <td style="padding-left: 10px;">
                            <span style="color: #858585;">
                                @item.City.Name
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <td width="20%" style="text-align: right;">
                            <strong></strong>
                        </td>
                        <td style="padding-left: 10px;">
                            <span style="color: #858585;">
                                @string.Format("Рассмотрение предложений: c " + item.CreatedDateTime.ToString("dd.MM.yyyy") + " до " + item.DateEnd.ToString("dd.MM.yyyy"))
                            </span>
                        </td>
                    </tr>

                    <tr>
                        <td width="20%" style="text-align: right;"></td>
                        <td style="padding-left: 10px; text-align: right;">
                            <a href="#" style="color: #eca62b;" onclick="hideTender(@item.Id)"><i class="glyphicon glyphicon-remove" style="color: #eca62b;"></i>Удалить</a>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
                <div class="rowWhite">

                </div>
    }

</table>

Project/MyTend/MyTend/Views/Tender/Created.cshtml
@model MyTend.Entites.Tender

@{
    ViewBag.Title = "Заявка отправлена!";
}
<br />
<div class="form-group" style="text-align: left">

	<h3><div style="color: #222222"> Ваша заявка успешно создана!</h3>
</div>

<h5>
    Заявка @Html.ActionLink(Model.Title, "Details", "Tender", new { id = Model.Id }, null) рассылается по исполнителям услуг, учитывая сферу деятельности и город.
<br />
	<br />	
  <img src="~/Content/images/lamp.png"width="16" height="20" />В случае, если заявку не одобрит модератор сайта, она будет удалена!</h5>
	<br />
	
<h4 style="color: #f99313;">Что дальше?</h4>

<br />


		 <div class="row">
            <div class="col-md-2"><img src="~/Content/images/NEW.svg" width="100" height="100" /></div>
            <div class="col-md-7" style="line-height:20px">
                <div style="font-weight: bold; font-size: 17px;">Робот Тендер  рассылает Вашу заявку по исполнителям.</div>
                <div style="font-size: 14px;"><br />	
                  В ближайшеевремя исполнители Event-услуг прочитают Вашу заявку и примут решение об участии в Вашем конкурсе на право исполнения услуги.
				  <br /><br />
				  Учитывая детали Вашей заявки и предложения коллег-конкурентов исполнитеи 
				  будут писать для Вас предложения оказания услуги, цены, бонусы.
				 
				  
                </div>
 </div> </div>
			<br />	
				 <div class="row">
            <div class="col-md-2"><img src="~/Content/images/ispolnitelimini.svg" width="100" height="100" /></div>
            <div class="col-md-7" style="line-height:20px">
                <div style="font-weight: bold; font-size: 17px;">Наблюдайте за поступлением предложений и выбирайте лучшее для себя!</div>
                <div style="font-size: 14px;"><br />	
                  В течении нескольких дней вы знакомитесь с поступившими предложениями и
				  и решаете, кто же станет победителем конкурса и сделал самое выгодное, интересное и заманчиваое предложение!
				  	<br /><br />
				  Рекомендуем вернуться на сайт через несколько часов и начать рассматривать предложения исполнителей в меню <br />	<br />	 <a href="~/Tender/My" class="btn-class-orange" style="color: black;"> Проверить предложения от исполнителей</a>
				  
                </div>
 </div> </div>
			
 
 <br /><br /><br /><br />
 
 
 

Project/MyTend/MyTend/Views/Tender/Winner.cshtml
@model MyTend.Models.WinnerTenderModel

@{
    ViewBag.Title = "Мои победы";
}


<h1 style="color: #000000;"><STRONG>Мои победы</STRONG></h1>
<h5 style="color: #777777;">В этом меню отображаются списки конкурсных торгов, где Вас выбрали победителем заявки.</h5>
 <hr style="margin-top: 2px;">
<div class="tabs">
   
    <div class="tab-content">
        <div class="tab-pane active" id="tab5-1">
            @if (Model.Tenders.Count > 0)
            {
                foreach (var item in Model.Tenders)
                {
                    <div class="row" id="tenderrow-@item.Id">
                        <div class="col-lg-2">
                            <div>
                                <a href="~/Tender/Details?id=@item.Id">
                                    <img src="~/Content/images/kats/@item.Theme.ImageName" width="90" height="100" />
                                </a>
                            </div>
                            <div>
                                @if (item.Winner != null && item.Winner.Login == ViewBag.UserLogin)
                                {
                                    
                                }
                            </div>
                        </div>
                        <div class="col-lg-10">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div style="padding-top: 20px">
                                        @Html.ActionLink(item.User.FullName, "Card", "Account", new { id = item.User.Email }, null) выбрал Вас победителем в торге @Html.ActionLink(item.Title, "Details", "Tender", new { id = item.Id }, null)
                                    </div>
                                    <div>
                                        Свяжитесь с ним по номеру: <span style="font-weight: bold; font-size: 20px; padding-left: 7px;">@item.User.Phone</span> 
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                }
            }
            else
            {
                <div>
                    Вас ещё не выбрали победителем конкурсного-торга.
                </div>
              
            }
        </div>
    </div>
</div>